package GestionUsuarios;

import FacturaPDF.facturaPDFScreen;
import Modelo.conexion;
import Modelo.sesion;
import java.awt.event.KeyEvent;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author angel
 */
public class gestionUsuariosScreen extends javax.swing.JFrame {

    private conexion con = new conexion();
    gestionUsuarios gu;
    gestionUsuariosScreen estaVentana = this;
    DefaultTableModel modelo, modelo1;

    /**
     * Creates new form gestionUsuariosScreen
     */
    public gestionUsuariosScreen(sesion s) {
        initComponents();
        initComponentsCustom();
        gu = new gestionUsuarios(s);
        this.fechaLabel.setText(getFechaActual());
        this.userNameLabel.setText(gu.getUsuario());
        this.setSize(601, 420);
//       
    }

    private String getFechaActual() {
        Date hoy = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MMM/yyyy");
        return formato.format(hoy);
    }

    private void initComponentsCustom() {
        setTableContador();
        setTableCajero();
    }

    private void setTableCajero() {
        modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Contraseña");
        modelo.addColumn("Sucursal");
        this.ListaCajeros.setModel(modelo);
        ListaUsuarios t = new ListaUsuarios();
        t.getDatos(modelo);
    }

    private void setTableContador() {
        modelo1 = new DefaultTableModel();
        modelo1.addColumn("Nombre");
        modelo1.addColumn("Contraseña");
        this.ListaContadores.setModel(modelo1);
        listaUsuariosContadores lis = new listaUsuariosContadores();
        lis.getDatos1(modelo1);
    }

    public void EliminarCajeros() {
        //Elimina la fila seleccionada
        try {
            String registro = (String) ListaCajeros.getValueAt(ListaCajeros.getSelectedRow(), ListaCajeros.getSelectedColumn());
            DefaultTableModel mod = (DefaultTableModel) ListaCajeros.getModel();
            mod.removeRow(ListaCajeros.getSelectedRow());
            Statement createst = con.conectar().createStatement();
            createst.executeUpdate("DELETE from usuarios where nombre = '" + registro + "';");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Seleccione fila " + JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public void EliminarContadores() {
        //Elimina la fila seleccionada
        try {
            String registro1 = (String) ListaContadores.getValueAt(ListaContadores.getSelectedRow(), ListaContadores.getSelectedColumn());
            DefaultTableModel mod1 = (DefaultTableModel) ListaContadores.getModel();
            mod1.removeRow(ListaContadores.getSelectedRow());
            Statement createst1 = con.conectar().createStatement();
            createst1.executeUpdate("DELETE from usuarios where nombre = '" + registro1 + "';");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Seleccione fila " + JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public void reiniciarJTable() {
        try {
            for (int i = 0; i < ListaCajeros.getRowCount(); i++) {
                modelo.removeRow(i);
                i -= 1;
            }
            for (int j = 0; j < ListaContadores.getRowCount(); j++) {
                modelo1.removeRow(j);
                j -= 1;
            }
            ListaUsuarios l1 = new ListaUsuarios();
            l1.getDatos(modelo);
            listaUsuariosContadores l2 = new listaUsuariosContadores();
            l2.getDatos1(modelo1);

        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSecciones = new javax.swing.JTabbedPane();
        TabContador = new javax.swing.JPanel();
        BtnGuardarContador = new javax.swing.JButton();
        ContadorNombreLabel = new javax.swing.JLabel();
        ContadorContrasenaInput = new javax.swing.JTextField();
        ContadorContrasenaLabel = new javax.swing.JLabel();
        ContadorNombreInput = new javax.swing.JTextField();
        ContadorNotasLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ContadorNotasInput = new javax.swing.JTextArea();
        TabCajero = new javax.swing.JPanel();
        CajeroNombreLabel = new javax.swing.JLabel();
        CajeroNombreInput = new javax.swing.JTextField();
        CajeroContrasenaLabel = new javax.swing.JLabel();
        CajeroContrasenaInput = new javax.swing.JTextField();
        CajeroSucursalLabel = new javax.swing.JLabel();
        CajeroSucursalInput = new javax.swing.JTextField();
        CajeroNotasLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        CajeroNotas = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaCajeros = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        ListaContadores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        fechaLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Top1 = new javax.swing.JLabel();
        Top2 = new javax.swing.JLabel();
        Top3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de Usuarios");
        setBounds(new java.awt.Rectangle(400, 100, 0, 0));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 405));
        setResizable(false);
        getContentPane().setLayout(null);

        PanelSecciones.setBackground(new java.awt.Color(255, 255, 255));

        TabContador.setBackground(new java.awt.Color(255, 255, 255));

        BtnGuardarContador.setBackground(new java.awt.Color(255, 255, 255));
        BtnGuardarContador.setText("GUARDAR");
        BtnGuardarContador.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        BtnGuardarContador.setPreferredSize(new java.awt.Dimension(110, 25));
        BtnGuardarContador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarContadorActionPerformed(evt);
            }
        });

        ContadorNombreLabel.setText("Nombre:");

        ContadorContrasenaInput.setToolTipText("Presione enter para continuar");
        ContadorContrasenaInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        ContadorContrasenaInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ContadorContrasenaInputKeyPressed(evt);
            }
        });

        ContadorContrasenaLabel.setText("Contraseña:");

        ContadorNombreInput.setToolTipText("Presione enter para continuar");
        ContadorNombreInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        ContadorNombreInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ContadorNombreInputKeyPressed(evt);
            }
        });

        ContadorNotasLabel.setText("Notas:");

        jScrollPane1.setBorder(null);

        ContadorNotasInput.setColumns(20);
        ContadorNotasInput.setLineWrap(true);
        ContadorNotasInput.setRows(5);
        ContadorNotasInput.setToolTipText("Presione enter para continuar");
        ContadorNotasInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        ContadorNotasInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ContadorNotasInputKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(ContadorNotasInput);

        javax.swing.GroupLayout TabContadorLayout = new javax.swing.GroupLayout(TabContador);
        TabContador.setLayout(TabContadorLayout);
        TabContadorLayout.setHorizontalGroup(
            TabContadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabContadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TabContadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContadorContrasenaInput)
                    .addComponent(ContadorNombreInput)
                    .addGroup(TabContadorLayout.createSequentialGroup()
                        .addGroup(TabContadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContadorNombreLabel)
                            .addComponent(ContadorContrasenaLabel)
                            .addComponent(ContadorNotasLabel)
                            .addGroup(TabContadorLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(BtnGuardarContador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );
        TabContadorLayout.setVerticalGroup(
            TabContadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabContadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ContadorNombreLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContadorNombreInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContadorContrasenaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContadorContrasenaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContadorNotasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnGuardarContador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        PanelSecciones.addTab("CONTADOR", TabContador);

        TabCajero.setBackground(new java.awt.Color(255, 255, 255));

        CajeroNombreLabel.setText("Nombre:");

        CajeroNombreInput.setToolTipText("Presione enter para continuar");
        CajeroNombreInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        CajeroNombreInput.setMinimumSize(new java.awt.Dimension(200, 19));
        CajeroNombreInput.setPreferredSize(new java.awt.Dimension(200, 19));
        CajeroNombreInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CajeroNombreInputKeyPressed(evt);
            }
        });

        CajeroContrasenaLabel.setText("Contraseña:");

        CajeroContrasenaInput.setToolTipText("Presione enter para continuar");
        CajeroContrasenaInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        CajeroContrasenaInput.setMinimumSize(new java.awt.Dimension(200, 19));
        CajeroContrasenaInput.setPreferredSize(new java.awt.Dimension(200, 19));
        CajeroContrasenaInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CajeroContrasenaInputKeyPressed(evt);
            }
        });

        CajeroSucursalLabel.setText("Sucursal:");

        CajeroSucursalInput.setToolTipText("Presione enter para continuar");
        CajeroSucursalInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        CajeroSucursalInput.setMinimumSize(new java.awt.Dimension(200, 19));
        CajeroSucursalInput.setPreferredSize(new java.awt.Dimension(200, 19));
        CajeroSucursalInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CajeroSucursalInputKeyPressed(evt);
            }
        });

        CajeroNotasLabel.setText("Notas:");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("GUARDAR");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jButton1.setPreferredSize(new java.awt.Dimension(110, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(null);

        CajeroNotas.setColumns(20);
        CajeroNotas.setLineWrap(true);
        CajeroNotas.setRows(5);
        CajeroNotas.setToolTipText("Presione enter para continuar");
        CajeroNotas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        CajeroNotas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CajeroNotasKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(CajeroNotas);

        javax.swing.GroupLayout TabCajeroLayout = new javax.swing.GroupLayout(TabCajero);
        TabCajero.setLayout(TabCajeroLayout);
        TabCajeroLayout.setHorizontalGroup(
            TabCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabCajeroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TabCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(CajeroNombreLabel)
                    .addComponent(CajeroContrasenaLabel)
                    .addComponent(CajeroSucursalLabel)
                    .addComponent(CajeroNotasLabel)
                    .addComponent(CajeroNombreInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CajeroContrasenaInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CajeroSucursalInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(TabCajeroLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        TabCajeroLayout.setVerticalGroup(
            TabCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabCajeroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CajeroNombreLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CajeroNombreInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CajeroContrasenaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CajeroContrasenaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CajeroSucursalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CajeroSucursalInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CajeroNotasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelSecciones.addTab("CAJERO", TabCajero);

        getContentPane().add(PanelSecciones);
        PanelSecciones.setBounds(10, 60, 260, 320);

        ListaCajeros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(ListaCajeros);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(290, 80, 300, 120);

        ListaContadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(ListaContadores);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(290, 250, 300, 120);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CAJEROS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(420, 60, 70, 14);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CONTADORES");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(410, 230, 69, 14);

        userNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        userNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        userNameLabel.setText("Nombre");
        getContentPane().add(userNameLabel);
        userNameLabel.setBounds(420, 10, 80, 14);

        fechaLabel.setBackground(new java.awt.Color(255, 255, 255));
        fechaLabel.setForeground(new java.awt.Color(255, 255, 255));
        fechaLabel.setText("30/JUL/2014");
        getContentPane().add(fechaLabel);
        fechaLabel.setBounds(420, 30, 61, 14);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestionUsuarios/images/logo.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 10, 50, 40);

        Top1.setBackground(new java.awt.Color(255, 255, 255));
        Top1.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        Top1.setForeground(new java.awt.Color(255, 255, 255));
        Top1.setText("Ordenador Net");
        getContentPane().add(Top1);
        Top1.setBounds(60, 20, 170, 26);

        Top2.setBackground(new java.awt.Color(255, 255, 255));
        Top2.setForeground(new java.awt.Color(255, 255, 255));
        Top2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Top2.setText("Plaza las Tiendas de Cancun");
        Top2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(Top2);
        Top2.setBounds(240, 10, 210, 20);

        Top3.setBackground(new java.awt.Color(255, 255, 255));
        Top3.setForeground(new java.awt.Color(255, 255, 255));
        Top3.setText("Local 6");
        getContentPane().add(Top3);
        Top3.setBounds(240, 30, 33, 14);

        jButton2.setText("ELIMINAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(400, 370, 100, 23);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogIn/images/Imagen1.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(510, 0, 80, 50);

        jButton3.setText("ELIMINAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(400, 200, 100, 23);

        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestionUsuarios/images/bg.jpg"))); // NOI18N
        getContentPane().add(backGround);
        backGround.setBounds(0, 0, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void BtnGuardarContadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarContadorActionPerformed
//        boolean ans=false;
//        ans=gu.agregarContador(this.ContadorNombreInput.getText().toUpperCase(), this.ContadorContrasenaInput.getText(),this.ContadorNotasInput.getText());
        String valores = ContadorNombreInput.getText().toUpperCase() + ",";
        valores += ContadorContrasenaInput.getText() + ",1,";
        valores += ContadorNotasInput.getText();
        System.out.println("antes de agregar=" + valores);
        con.agregar("usuarios", "nombre,password,permisos,notas", valores);
        System.out.println("Despues de agregar");
        reiniciarJTable();
        ContadorContrasenaInput.setText("");
        ContadorNotasInput.setText("");
        ContadorNombreInput.setText("");
    }//GEN-LAST:event_BtnGuardarContadorActionPerformed

    private void ContadorNombreInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContadorNombreInputKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ContadorContrasenaInput.requestFocus();
        }
    }//GEN-LAST:event_ContadorNombreInputKeyPressed

    private void ContadorContrasenaInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContadorContrasenaInputKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ContadorNotasInput.requestFocus();
        }
    }//GEN-LAST:event_ContadorContrasenaInputKeyPressed

    private void CajeroNombreInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CajeroNombreInputKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            CajeroContrasenaInput.requestFocus();
        }
    }//GEN-LAST:event_CajeroNombreInputKeyPressed

    private void CajeroContrasenaInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CajeroContrasenaInputKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            CajeroSucursalInput.requestFocus();
        }
    }//GEN-LAST:event_CajeroContrasenaInputKeyPressed

    private void CajeroSucursalInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CajeroSucursalInputKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            CajeroNotas.requestFocus();
        }
    }//GEN-LAST:event_CajeroSucursalInputKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String valores = CajeroNombreInput.getText().toUpperCase() + ",";
        valores += CajeroContrasenaInput.getText() + ",0,";
        valores += CajeroSucursalInput.getText() + ",";
        valores += CajeroNotas.getText();
        System.out.println("antes de agregar=" + valores);
        con.agregar("usuarios", "nombre,password,permisos,sucursal,notas", valores);
        System.out.println("Despues de agregar");
        reiniciarJTable();
        CajeroContrasenaInput.setText("");
        CajeroNombreInput.setText("");
        CajeroNotas.setText("");
        CajeroSucursalInput.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ContadorNotasInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContadorNotasInputKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BtnGuardarContador.requestFocus();
        }
    }//GEN-LAST:event_ContadorNotasInputKeyPressed

    private void CajeroNotasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CajeroNotasKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButton1.requestFocus();
        }
    }//GEN-LAST:event_CajeroNotasKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            EliminarCajeros();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            EliminarContadores();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            FacturaPDF.facturaPDFScreen pdf = new facturaPDFScreen();
            pdf.show();
            this.hide();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestionUsuariosScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestionUsuariosScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestionUsuariosScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestionUsuariosScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestionUsuariosScreen(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardarContador;
    private javax.swing.JTextField CajeroContrasenaInput;
    private javax.swing.JLabel CajeroContrasenaLabel;
    private javax.swing.JTextField CajeroNombreInput;
    private javax.swing.JLabel CajeroNombreLabel;
    private javax.swing.JTextArea CajeroNotas;
    private javax.swing.JLabel CajeroNotasLabel;
    private javax.swing.JTextField CajeroSucursalInput;
    private javax.swing.JLabel CajeroSucursalLabel;
    private javax.swing.JTextField ContadorContrasenaInput;
    private javax.swing.JLabel ContadorContrasenaLabel;
    private javax.swing.JTextField ContadorNombreInput;
    private javax.swing.JLabel ContadorNombreLabel;
    private javax.swing.JTextArea ContadorNotasInput;
    private javax.swing.JLabel ContadorNotasLabel;
    private javax.swing.JTable ListaCajeros;
    private javax.swing.JTable ListaContadores;
    private javax.swing.JTabbedPane PanelSecciones;
    private javax.swing.JPanel TabCajero;
    private javax.swing.JPanel TabContador;
    private javax.swing.JLabel Top1;
    private javax.swing.JLabel Top2;
    private javax.swing.JLabel Top3;
    private javax.swing.JLabel backGround;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
