/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GestionFacturas;

/**
 *
 * @author angel
 */
public class gestionFacturasScreen extends javax.swing.JFrame {

    /**
     * Creates new form gestionFacturasScreen
     */
    public gestionFacturasScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Top4 = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Top1 = new javax.swing.JLabel();
        Top2 = new javax.swing.JLabel();
        Top3 = new javax.swing.JLabel();
        BtnGenerar = new javax.swing.JButton();
        BtnBuscar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        Top4.setBackground(new java.awt.Color(255, 255, 255));
        Top4.setForeground(new java.awt.Color(255, 255, 255));
        Top4.setText("FECHA:");
        getContentPane().add(Top4);
        Top4.setBounds(510, 10, 49, 15);

        Fecha.setBackground(new java.awt.Color(255, 255, 255));
        Fecha.setForeground(new java.awt.Color(255, 255, 255));
        Fecha.setText("30/JUL/2014");
        getContentPane().add(Fecha);
        Fecha.setBounds(510, 30, 78, 15);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestionUsuarios/images/logo.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 10, 50, 40);

        Top1.setBackground(new java.awt.Color(255, 255, 255));
        Top1.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        Top1.setForeground(new java.awt.Color(255, 255, 255));
        Top1.setText("Ordenador Net");
        getContentPane().add(Top1);
        Top1.setBounds(60, 20, 170, 24);

        Top2.setBackground(new java.awt.Color(255, 255, 255));
        Top2.setForeground(new java.awt.Color(255, 255, 255));
        Top2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Top2.setText("Plaza las Tiendas de Cancun");
        Top2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(Top2);
        Top2.setBounds(270, 10, 210, 20);

        Top3.setBackground(new java.awt.Color(255, 255, 255));
        Top3.setForeground(new java.awt.Color(255, 255, 255));
        Top3.setText("Local 6");
        getContentPane().add(Top3);
        Top3.setBounds(270, 30, 49, 15);

        BtnGenerar.setBackground(new java.awt.Color(255, 255, 255));
        BtnGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestionFacturas/images/generar.png"))); // NOI18N
        BtnGenerar.setAlignmentY(0.0F);
        BtnGenerar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnGenerar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        BtnGenerar.setPreferredSize(new java.awt.Dimension(100, 80));
        BtnGenerar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/GestionFacturas/images/generarHover.png"))); // NOI18N
        BtnGenerar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(BtnGenerar);
        BtnGenerar.setBounds(490, 110, 100, 80);

        BtnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        BtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestionFacturas/images/buscar.png"))); // NOI18N
        BtnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnBuscar.setPreferredSize(new java.awt.Dimension(100, 80));
        BtnBuscar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/GestionFacturas/images/buscarHover.png"))); // NOI18N
        BtnBuscar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(BtnBuscar);
        BtnBuscar.setBounds(490, 190, 100, 80);

        BtnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        BtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestionFacturas/images/cancelar.png"))); // NOI18N
        BtnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEliminar.setPreferredSize(new java.awt.Dimension(100, 80));
        BtnEliminar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/GestionFacturas/images/cancelarHover.png"))); // NOI18N
        BtnEliminar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(BtnEliminar);
        BtnEliminar.setBounds(490, 270, 100, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestionFacturas/images/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestionFacturasScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestionFacturasScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestionFacturasScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestionFacturasScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestionFacturasScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGenerar;
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel Top1;
    private javax.swing.JLabel Top2;
    private javax.swing.JLabel Top3;
    private javax.swing.JLabel Top4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
