package LogIn;

import Modelo.conexion;

/**
 *
 * @author angel
 */
public class loginScreen extends javax.swing.JFrame {

    /**
     * Creates new form loginScreen
     */
    public loginScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userInput = new javax.swing.JTextField();
        passInput = new javax.swing.JPasswordField();
        huella = new javax.swing.JLabel();
        logotipo = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBounds(new java.awt.Rectangle(500, 100, 0, 0));
        setMaximumSize(new java.awt.Dimension(400, 600));
        setMinimumSize(new java.awt.Dimension(400, 600));
        setName("divMain"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        userInput.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        userInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userInput.setText("USUARIO");
        userInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userInputFocusGained(evt);
            }
        });
        getContentPane().add(userInput);
        userInput.setBounds(50, 270, 300, 40);

        passInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passInput.setText("password");
        passInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passInputFocusGained(evt);
            }
        });
        getContentPane().add(passInput);
        passInput.setBounds(50, 350, 300, 40);

        huella.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogIn/images/fp.png"))); // NOI18N
        huella.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                huellaMouseClicked(evt);
            }
        });
        getContentPane().add(huella);
        huella.setBounds(150, 450, 100, 110);

        logotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogIn/images/lg.png"))); // NOI18N
        getContentPane().add(logotipo);
        logotipo.setBounds(120, 30, 170, 180);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogIn/images/bg.jpg"))); // NOI18N
        fondo.setText("jLabel1");
        fondo.setAlignmentY(0.0F);
        fondo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 400, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void huellaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_huellaMouseClicked
        manejarLogin();
        if(evt.isMetaDown())
            huella.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogIn/images/fpNegated.png")));
        else if (evt.isAltDown())
            huella.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogIn/images/fp.png")));
        else
            huella.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogIn/images/fpAproved.png")));
    }//GEN-LAST:event_huellaMouseClicked
    
    private void manejarLogin(){
        String user=this.userInput.getText(),pass=this.passInput.getText();
        sesion s=new sesion();
    }
    
    private void userInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userInputFocusGained
        this.userInput.selectAll();
    }//GEN-LAST:event_userInputFocusGained

    private void passInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passInputFocusGained
        this.passInput.selectAll();
    }//GEN-LAST:event_passInputFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel huella;
    private javax.swing.JLabel logotipo;
    private javax.swing.JPasswordField passInput;
    private javax.swing.JTextField userInput;
    // End of variables declaration//GEN-END:variables
    private conexion con;
}
