/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventas;

import Modelo.conexion;
import PanelFondo.panelFondo;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shary
 */
public class Venta extends javax.swing.JFrame {

    private conexion con = new conexion();
    private int registros,bandera=0;
    private String registro_buqueda;
    private String registro_precio;
    private String rfc, org;
    private int factura;
    private panelFondo panel;
    DefaultTableModel modelo;
    ventaClass venta = new ventaClass();

    /**
     * Creates new form Venta
     */
    public Venta() {
        ImageIcon img=new ImageIcon(getClass().getResource("/Ventas/images/bg.jpg"));
        setContentPane(panel=new panelFondo(img));
        initComponents();
        this.setLocationRelativeTo(null);
        id_folioVenta();
        folio.setText(String.valueOf(registros + 1));
        this.setSize(470, 425);
        modelo = new DefaultTableModel();
        modelo.addColumn("Folio");
        modelo.addColumn("Producto");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio");
        this.jTable1.setModel(modelo);
        producto.requestFocus();
        this.getContentPane().setBackground(Color.WHITE);
    }
    
    private 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        folio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rfc_cliente = new javax.swing.JTextField();
        compañia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        domicilio = new javax.swing.JTextField();
        ciudad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        estado = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        producto = new javax.swing.JTextField();
        cantidad = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventas");
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        setForeground(new java.awt.Color(0, 0, 0));

        folio.setEditable(false);
        folio.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        folio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Folio");

        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 1, true));
        jTable1.setFont(new java.awt.Font("Times New Roman", 3, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 1, true));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Compañia");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 68, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("RFC");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 40, -1, -1));

        rfc_cliente.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rfc_cliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rfc_cliente.setToolTipText("Presione enter para continuar");
        rfc_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rfc_clienteKeyPressed(evt);
            }
        });
        jPanel1.add(rfc_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 277, -1));

        compañia.setEditable(false);
        compañia.setBackground(java.awt.Color.white);
        compañia.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        compañia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        compañia.setToolTipText("Presione enter para continuar");
        compañia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                compañiaKeyPressed(evt);
            }
        });
        jPanel1.add(compañia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 277, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DATOS CLIENTE");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 12, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Domicilio");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("Ciudad");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        domicilio.setEditable(false);
        domicilio.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        domicilio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        domicilio.setToolTipText("Presione enter para continuar");
        domicilio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                domicilioKeyPressed(evt);
            }
        });
        jPanel1.add(domicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 277, -1));

        ciudad.setEditable(false);
        ciudad.setBackground(java.awt.Color.white);
        ciudad.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ciudad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ciudad.setToolTipText("Presione enter para continuar");
        ciudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ciudadKeyPressed(evt);
            }
        });
        jPanel1.add(ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 277, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Estado");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("Email");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        estado.setEditable(false);
        estado.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        estado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        estado.setToolTipText("Presione enter para continuar");
        estado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                estadoKeyPressed(evt);
            }
        });
        jPanel1.add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 277, -1));

        email.setEditable(false);
        email.setBackground(java.awt.Color.white);
        email.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email.setToolTipText("Presione enter para continuar");
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailKeyPressed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 277, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 1, true));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Codigo Producto");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 111, 23));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 111, 23));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setText("Eliminar");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 1, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 121, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Precio Unitario");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 111, 23));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("Añadir");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 121, -1));

        producto.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        producto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        producto.setToolTipText("Presione enter para continuar");
        producto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                productoKeyPressed(evt);
            }
        });
        jPanel2.add(producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 144, -1));

        cantidad.setEditable(false);
        cantidad.setBackground(new java.awt.Color(255, 255, 255));
        cantidad.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cantidad.setToolTipText("Presione enter para continuar");
        cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantidadKeyPressed(evt);
            }
        });
        jPanel2.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 144, -1));

        precio.setEditable(false);
        precio.setBackground(new java.awt.Color(255, 255, 255));
        precio.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        precio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        precio.setToolTipText("Presione enter para continuar");
        precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                precioKeyPressed(evt);
            }
        });
        jPanel2.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 144, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton3.setText("Finalizar venta");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 1, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 121, -1));

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenu1.setText("Nueva Venta");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu4.setText("Factura");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenu4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()

                        .addGap(335, 335, 335)

                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(folio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(folio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)

                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))

        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void id_folioVenta() {
        try {
            PreparedStatement pstm = (PreparedStatement) con.conectar().prepareStatement("SELECT id_folio as folio FROM ventas ORDER BY id_folio DESC LIMIT 1; ");
            ResultSet res = pstm.executeQuery();
            res.next();
            registros = res.getInt("folio");
            res.close();
        } catch (Exception e) {
        }
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String pro = "", pre = "", can = "";
        pro = producto.getText().toUpperCase();
        can = cantidad.getText().toUpperCase();
        pre = precio.getText().toUpperCase();
        if (factura == 1) {
            if ("".equals(pro) || "".equals(can) || "".equals(pre) || "".equals(rfc) || "".equals(org)) {
                JOptionPane.showMessageDialog(null, "Celdas vacias...!");
            } else {
                String[] Datos = new String[4];
                Datos[0] = folio.getText();
                Datos[1] = producto.getText();
                Datos[2] = cantidad.getText();
                Datos[3] = precio.getText();
                modelo.addRow(Datos);
                producto.setText("");
                cantidad.setText("");
                precio.setText("");
                producto.requestFocus();
            }
        } else if (factura == 0) {
            if ("".equals(pro) || "".endsWith(can) || "".equals(pre)) {
                JOptionPane.showMessageDialog(null, "Celdas vacias...!");
            } else {
                String[] Datos = new String[4];
                Datos[0] = folio.getText();
                Datos[1] = producto.getText();
                Datos[2] = cantidad.getText();
                Datos[3] = precio.getText();
                modelo.addRow(Datos);
                producto.setText("");
                cantidad.setText("");
                precio.setText("");
                producto.requestFocus();
            }

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    public void Eliminar() {
        //Elimina la fila seleccionada
        try {
            String registro = (String) jTable1.getValueAt(jTable1.getSelectedRow(), jTable1.getSelectedColumn());
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            modelo.removeRow(jTable1.getSelectedRow());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Seleccione fila " + JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Eliminar();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void validarRFC() {
        int v = 0;
        String RFC = "";
        RFC = rfc_cliente.getText().toUpperCase();
        if (RFC.length() < 13 || RFC.length() > 13) {
            JOptionPane.showMessageDialog(null, "Ingrese un RFC valido", "RFC NO VALIDO", JOptionPane.INFORMATION_MESSAGE);
            rfc_cliente.setText("");
            rfc_cliente.requestFocus();
        } else {
            if (!RFC.matches("^[a-zA-Z]{4}.*$")) {
                RFC = "XXXX" + RFC.substring(4);
                v = 1;
            }
            if (!RFC.matches("^.{4}\\d{6}.*$")) {
                RFC = RFC.substring(0, 4) + "000000" + RFC.substring(10);
                v = 1;
            }
            if (v == 1) {
                JOptionPane.showMessageDialog(null, RFC + " Invalido");
                rfc_cliente.setText("");
                rfc_cliente.requestFocus();
            } else {
//                JOptionPane.showMessageDialog(null, RFC + " Valido");
                con.busquedaCliente("clientes", "rfc", rfc_cliente.getText().toUpperCase());
                if ("".equals(con.registro_busqueda)) {
                    compañia.setEditable(true);
                    domicilio.setEditable(true);
                    ciudad.setEditable(true);
                    estado.setEditable(true);
                    email.setEditable(true);
                    bandera=1;
//                    con.agregar("clientes", "rfc,nombre_cliente,domicilio,ciudad,estado,email", rfc_cliente.getText().toUpperCase() + "," + compañia.getText().toUpperCase() + "," + domicilio.getText().toUpperCase() + "," + ciudad.getText().toUpperCase() + "," + estado.getText().toUpperCase() + "," + email.getText());
                } else {
                    compañia.setText(con.registro_busqueda1);
                    domicilio.setText(con.registro_busqueda2);
                    ciudad.setText(con.registro_busqueda3);
                    estado.setText(con.registro_busqueda4);
                    email.setText(con.registro_busqueda5);
                    bandera=0;
                }
                rfc = RFC;
//                compañia.setEditable(true);
//                compañia.requestFocus();
                factura = 1;
            }
        }

    }

    public void reiniciarJTable() {
        try {
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                modelo.removeRow(i);
                i -= 1;
            }
        } catch (Exception e) {
        }
    }
    
    public void clear()
    {
        compañia.setText("");
        producto.setText("");
        precio.setText("");
        cantidad.setText("");
        rfc_cliente.setText("");
        domicilio.setText("");
        ciudad.setText("");
        estado.setText("");
        email.setText("");
        id_folioVenta();
    }


    private void rfc_clienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rfc_clienteKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                validarRFC();
            } catch (HeadlessException e) {
            }
        }
    }//GEN-LAST:event_rfc_clienteKeyPressed

    private void productoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productoKeyPressed
        String aux1;
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            aux1 = producto.getText();
            venta.busqueda_producto(aux1, producto, precio);
//            productos+=producto.getText().concat(",");
            cantidad.setEditable(true);
            cantidad.requestFocus();
        }

    }//GEN-LAST:event_productoKeyPressed

    private void precioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioKeyPressed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        this.setSize(470, 670);
        rfc_cliente.requestFocus();
        producto.setEditable(false);
        precio.setEditable(false);
        cantidad.setEditable(false);
        jButton1.setEnabled(false);
        factura = 1;
    }//GEN-LAST:event_jMenu4MouseClicked

    private void compañiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_compañiaKeyPressed
        // TODO add your handling code here
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            org = compañia.getText().toUpperCase();
            domicilio.requestFocus();
        }
    }//GEN-LAST:event_compañiaKeyPressed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        this.setSize(470, 425);
        producto.requestFocus();
        producto.setEditable(true);
        precio.setEditable(true);
        cantidad.setEditable(true);
        jButton1.setEnabled(true);
        factura = 0;
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String productos = "", precios = "", cantidades = "";
        double total = 0, subtotal = 0;
        int n = jTable1.getRowCount();
        for (int i = 0; i < n; i++) {
            productos += jTable1.getValueAt(i, 1).toString().concat("|");
            cantidades += jTable1.getValueAt(i, 2).toString().concat("|");
            precios += jTable1.getValueAt(i, 3).toString().concat("|");
            subtotal += Integer.parseInt(jTable1.getValueAt(i, 2).toString()) * Double.parseDouble(jTable1.getValueAt(i, 3).toString());
        }
        total = subtotal + (subtotal * 16 / 100);
//         JOptionPane.showMessageDialog(null, productos+"  "+cantidades+"   "+  precios+"   "+subtotal + " "+total);
        String val = "";
        if (factura == 1) {
            if (subtotal >= 100) {
                val += rfc + ",";
                val += compañia.getText().toUpperCase() + ",";
                val += productos + ",";
                val += cantidades + ",";
                val += precios + ",";
                val += subtotal + ",";
                val += total + ",";
                val += 1;
                con.agregar("ventas", "rfc_cliente,empresa,producto,cantidad,precio_unitario,subtotal,total,factura", val);
            } else {
//                JOptionPane.showMessageDialog(null, "La compra debe ser >= $100.00 pesos");
            }
        } else if (factura == 0) {
            val += productos + ",";
            val += cantidades + ",";
            val += precios + ",";
            val += subtotal + ",";
            val += total + ",";
            val += 0;
            con.agregar("ventas", "producto,cantidad,precio_unitario,subtotal,total,factura", val);
//       JOptionPane.showMessageDialog(null, val);
        }
        if(bandera==1)
        {
            con.agregar("clientes", "rfc,nombre_cliente,domicilio,ciudad,estado,email", rfc_cliente.getText().toUpperCase() + "," + compañia.getText().toUpperCase() + "," + domicilio.getText().toUpperCase() + "," + ciudad.getText().toUpperCase() + "," + estado.getText().toUpperCase() + "," + email.getText());
        }
        reiniciarJTable();
        clear();

//        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButton1.requestFocus();
        }
    }//GEN-LAST:event_cantidadKeyPressed

    private void domicilioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_domicilioKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ciudad.requestFocus();
        }
    }//GEN-LAST:event_domicilioKeyPressed

    private void ciudadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ciudadKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            estado.requestFocus();
        }
    }//GEN-LAST:event_ciudadKeyPressed

    private void estadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_estadoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            email.requestFocus();
        }
    }//GEN-LAST:event_estadoKeyPressed

    private void emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButton3.requestFocus();
        }
    }//GEN-LAST:event_emailKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField ciudad;
    private javax.swing.JTextField compañia;
    private javax.swing.JTextField domicilio;
    private javax.swing.JTextField email;
    private javax.swing.JTextField estado;
    private javax.swing.JTextField folio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField precio;
    private javax.swing.JTextField producto;
    private javax.swing.JTextField rfc_cliente;
    // End of variables declaration//GEN-END:variables
}
